base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

myauth/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views import (
    MyAccountDetailView,
    MyAccountUpdateView,
    UserRegistrationView,
    EmailConfirmationSentView,
    UserConfirmEmailView,
    EmailConfirmedView,
    EmailConfirmationFailedView,
    MyLoginView,
)

app_name = 'myauth'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('email_confirmation_sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confiramation_failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    path(
        'login/',
        MyLoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login'
    ),

    path('logout/', LogoutView.as_view(), name='logout'),

    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='myauth/password_change.html',
            success_url=reverse_lazy('myauth:password_change_done')
        ),
        name='password_change'
    ),

    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='myauth/password_change_done.html',
        ),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='myauth/password_reset.html',
            email_template_name='myauth/password_reset_email.html',
            success_url=reverse_lazy('myauth:password_reset_done'),
        ),
        name='password_reset'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='myauth/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='myauth/password_reset_confirm.html',
            success_url=reverse_lazy('myauth:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='myauth/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path('my_account/<int:pk>/', MyAccountDetailView.as_view() , name='my_account'),
    path('my_account/update/', MyAccountUpdateView.as_view(), name='my_account_update'),
]

myauth/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models


class Profile(models.Model):
    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'
        ordering = ['user',]

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='пользователь')
    avatar = models.ImageField(blank=True, default='users/avatars/default.png',
                               upload_to=f'users/avatars/%Y/%m/%d/', validators=[
            FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg')),
    ], verbose_name='аватар')
    birth_date = models.DateField(null=True, blank=True, verbose_name='дата рождения')
    bio = models.TextField(max_length=500, blank=True, verbose_name='о себе')


    def __str__(self):
        return self.user.username

myauth/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.db import transaction
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView

from .forns import UserRegistrationForm, ProfileUpdateForm, UserUpdateForm
from .models import Profile


class MyAccountDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'myauth/my_account.html'
    context_object_name = 'profile'

class MyAccountUpdateView(UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'myauth/my_account_update.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование профиля пользователя {self.request.user.username}'
        if self.request.POST:
            context['user_form'] = UserUpdateForm(self.request.POST, instance=self.request.user)
        else:
            context['user_form'] = UserUpdateForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context['user_form']
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({'user_form': user_form})
                return self.render_to_response(context)
        return super(MyAccountUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('myauth:my_account', kwargs={'pk': self.object.pk})


class MyLoginView(LoginView):
    """Представление аутентификации пользователя на сайте."""
    def get_success_url(self):
        url = self.get_redirect_url()
        return url or reverse('myauth:my_account', kwargs={'pk': self.request.user.pk})


class UserRegistrationView(CreateView):
    """Представление регистрации пользователя на сайте."""
    form_class = UserRegistrationForm
    template_name = 'myauth/user_registration.html'
    success_url = reverse_lazy('myauth:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        profile = Profile.objects.create(user=user)
        profile.user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('myauth:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current()
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            'cars.auth@gmail.com',
            [user.email],
            fail_silently=False,
        )
        return redirect(reverse('myauth:email_confirmation_sent'))


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect(reverse('myauth:email_confirmed'))
        else:
            return redirect(reverse('myauth:email_confirmation_failed'))


class EmailConfirmationSentView(TemplateView):
    """Представление уведомления об отправке письма для подтверждения по электронной почте."""
    template_name = 'myauth/email_confirmation_sent.html'


class EmailConfirmedView(TemplateView):
    """Представление успешного подтверждения электронной почты."""
    template_name = 'myauth/email_confirmed.html'


class EmailConfirmationFailedView(TemplateView):
    """Представление ошибки подтверждения по электронной почте."""
    template_name = 'myauth/email_confirmation_failed.html'

myauth/templates/myauth/email_confirmation_failed.html
{% extends 'base.html' %}

{% block title %}
    Ошибка подтверждения по электронной почте
{% endblock %}

{% block body %}
    <h1>Ошибка подтверждения по электронной почте</h1>
    <div>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек.
        Пожалуйста, <a href="{% url 'myauth:register' %}">зарегистрируйтесь снова.</a></div>
{% endblock %}

myauth/templates/myauth/email_confirmation_sent.html
{% extends 'base.html' %}

{% block title %}
    Письмо подтверждения отправлено
{% endblock %}

{% block body %}
    <h1>Письмо подтверждения отправлено</h1>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
{% endblock %}

myauth/templates/myauth/email_confirmed.html
{% extends 'base.html' %}

{% block title %}
    Электронная почта подтверждена
{% endblock %}

{% block body %}
    <h1>Электронная почта подтверждена</h1>
    <p>Ваш адрес электронной почты успешно подтверждён. Спасибо за регистрацию!</p>
    <div>
        <a href="{% url 'myauth:login' %}">Можете войти на сайт</a>
    </div>
{% endblock %}

myauth/templates/myauth/login.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block body %}
    <h1>Авторизация на сайте</h1>
    {% if form.errors %}
        <p>Имя пользователя или пароль указаны неверно. Попробуйте заново</p>
    {% else %}
        <p>Используйте форму для входа</p>
    {% endif %}

    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
        </form>
    </div>

    <div>
        <a href="{% url 'myauth:password_reset' %}">Забыли пароль?</a>
    </div>

    <div>
        <a href="{% url 'myauth:register' %}">Ещё не зарегистрированы на сайте?</a>
    </div>

{% endblock %}

myauth/templates/myauth/my_account.html
{% extends 'base.html' %}

{% block title %}
    Личный кабинет
{% endblock %}

{% block body %}
    <h1>Личный кабинет</h1><br>

    <h2>Информация о пользователе</h2>

    <i>Заходил {{ profile.user.last_login }}</i>

    <div>
        <figure>
            <img src="{{ profile.avatar.url }}" width="150" height="150" alt="{{ profile }}">
        </figure>
    </div>

    <p>Логин: {{ profile.user.username }}</p>

    <div>
        {% if profile.user.first_name %}
        <p>Имя: {{ profile.user.first_name }}</p>
        {% endif %}
    </div>

    <div>
        {% if profile.user.last_name %}
        <p>Фамилия: {{ profile.user.last_name }}</p>
        {% endif %}
    </div>

    <div>
        {% if profile.birth_date %}
        <p>Дата рождения: {{ profile.birth_date }}</p>
        {% endif %}
    </div>

    <p>Эл. почта: {{ profile.user.email }}</p>

     <div>
        {% if profile.bio %}
        <p>О себе: {{ profile.bio }}</p>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'myauth:logout' %}">Выйти</a>
    </div>

    <div>
        <a href="{% url 'myauth:password_change' %}">Сменить пароль</a>
    </div>

    <div>
        <a href="{% url 'myauth:my_account_update' %}">Редактировать профиль</a>
    </div>

{% endblock %}

myauth/templates/myauth/my_account_update.html
{% extends 'base.html' %}>

{% block body %}
    <h1>Редактирование профиля</h1>
    <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ form.as_p }}
    <button type="submit">Изменить данные</button>
    </form>
{% endblock %}

myauth/templates/myauth/password_change.html
{% extends 'base.html' %}

{% block title %}
    Смена пароля
{% endblock %}

{% block body %}
    <h1>Смена пароля</h1>
    <p>Воспользуйтесь данной формой для смены пароля</p>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Change</button>
        </form>
    </div>

{% endblock %}

myauth/templates/myauth/password_change_done.html
{% extends 'base.html' %}

{% block title %}
    Пароль изменён
{% endblock %}

{% block body %}
    <h1>Пароль изменён</h1>
    <p>Ваш пароль был успешно изменён</p><br>
    <div>
        <a href="{% url 'myauth:login' %}">Вернуться в личный кабинет</a>
    </div>

{% endblock %}

myauth/templates/myauth/password_reset.html
{% extends 'base.html' %}

{% block title %}
    Запрос на восстановление пароля на сайте
{% endblock %}

{% block body %}
    <h1>Запрос на восстановление пароля на сайте</h1>
    <p>Укажите адрес электоронной почты для восстановления пароля</p>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
        </form>
    </div>

{% endblock %}

myauth/templates/myauth/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
    Пароль восстановлен
{% endblock %}

{% block body %}
    <h1>Пароль восстановлен</h1>
    <p>Новый пароль был успешно установлен. Вы можете <a href="{% url 'myauth:login' %}">войти</a></p>
{% endblock %}

myauth/templates/myauth/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    Восстановление пароля
{% endblock %}

{% block body %}
    <h1>Восстановление пароля</h1>
    {% if validlink %}
    <p>Введите новый пароль дважды:</p>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить пароль</button>
    </form>
    {% else %}
    <p>Ссылка на восстановление пароля недоступна. Возможно, вы уже использовали её.
    Сделайте новый запрос на восстановление пароля.</p>
    {% endif %}
{% endblock %}

myauth/templates/myauth/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    Восстановление пароля
{% endblock %}

{% block body %}
    <h1>Восстановление пароля</h1>
    <p>На вашу электронную почту было отправлено письмо с инструкциями по восстановлению пароля</p>
{% endblock %}

myauth/templates/myauth/password_reset_email.html
{% block reset_link %}
Имя пользователя: {{ user.get_username }}
От вашего имени был сделан запрос на восстановление пароля через электронную почту {{ email }}.
Для восстановления пароля перейдите по ссылке: {{ protocol }}://{{ domain }}{% url 'myauth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

myauth/templates/myauth/user_registration.html
{% extends 'base.html' %}

{% block title %}
    Регистрация на сайте
{% endblock %}

{% block body %}
    <h1>Регистрация на сайте</h1>
    <div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
        </form>
    </div>

{% endblock %}