base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

shop/urls.py
from django.urls import path

from .views import (
    BrandsListView,
    BrandDetailsView,
    CarsListView,
    CarDetailsView,
)

app_name = 'shop'

urlpatterns = [
    path('brands/', BrandsListView.as_view(), name='brands'),
    path('brands/<int:pk>/', BrandDetailsView.as_view(), name='brand_details'),
    path('cars/', CarsListView.as_view(), name='cars'),
    path('cars/<int:pk>/', CarDetailsView.as_view(), name='car_details'),
]

shop/models.py
from django.core.validators import FileExtensionValidator
from django.db import models


def brand_image_directory_path(instance: 'Brand', filename: str) -> str:
    return 'brands/{title}/image/{filename}'.format(
        title=instance.title,
        filename=filename
    )

def car_preview_directory_path(instance: 'Car', filename: str) -> str:
    return 'cars/{brand}/{model}/preview/{filename}'.format(
        brand=instance.brand,
        model=instance.model,
        filename=filename,
    )

def car_images_directory_path(instance: 'CarImage', filename: str) -> str:
    return 'cars/{brand}/{model}/images/{filename}'.format(
        brand=instance.car.brand,
        model=instance.car.model,
        filename=filename
    )


class Brand(models.Model):
    """Модель марки автомобиля."""
    class Meta:
        verbose_name = 'бренд'
        verbose_name_plural = 'бренды'
        ordering = ['title',]
        indexes = [models.Index(fields=('title',))]

    title = models.CharField(max_length=100, verbose_name='название')
    brand_country = models.CharField(max_length=30, default='Китай', verbose_name='страна бренда')
    description = models.TextField(blank=True, verbose_name='описание')
    image = models.ImageField(upload_to=brand_image_directory_path, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))
    ], verbose_name='изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')

    def __str__(self):
        return self.title


class Car(models.Model):
    """Модель автомобиля."""
    class Meta:
        verbose_name = 'автомобиль'
        verbose_name_plural = 'автомобили'
        ordering = ['brand', 'model', '-price',]
        indexes = [models.Index(fields=('brand', 'model', '-price'))]


    CAR_CLASS_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),
        ('S', 'S'),
        ('M', 'M'),
        ('J', 'J'),
    )

    TRANSMISSION_CHOICES = (
        ('механика', 'Механика'),
        ('автомат', 'Автомат'),
        ('робот', 'Робот'),
        ('вариатор', 'Вариатор'),
    )

    DRIVE_CHOICES = (
        ('задний', 'Задний'),
        ('передний', 'Передний'),
        ('полный', 'Полный'),
    )

    price = models.DecimalField(max_digits=8, decimal_places=0, verbose_name='цена')
    discount = models.PositiveSmallIntegerField(default=0, verbose_name='скидка')
    preview = models.ImageField(blank=True, upload_to=car_preview_directory_path, validators=[
        FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))
    ], verbose_name='превью')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='brand', verbose_name='бренд')
    model = models.CharField(max_length=100, verbose_name='модель')
    car_class = models.CharField(max_length=1, choices=CAR_CLASS_CHOICES, verbose_name='класс автомобиля')
    doors_qty = models.PositiveSmallIntegerField(verbose_name='количество дверей')
    seats_qty = models.PositiveSmallIntegerField(verbose_name='количеств мест')
    transmission = models.CharField(max_length=8, choices=TRANSMISSION_CHOICES, verbose_name='коробка')
    engine_power = models.PositiveSmallIntegerField(verbose_name='мощность двигателя (л.с.)')
    engine_capacity = models.DecimalField(max_digits=3, decimal_places=1, verbose_name='объём двигателя (л)')
    drive = models.CharField(max_length=8, choices=DRIVE_CHOICES, verbose_name='привод')
    consumption = models.DecimalField(max_digits=3, decimal_places=1, verbose_name='расход')
    trunk_volume = models.PositiveSmallIntegerField(verbose_name='объём багажника (л)')
    fuel_tank_capacity = models.PositiveSmallIntegerField(verbose_name='объём топливного бака (л)')
    max_speed = models.PositiveSmallIntegerField(verbose_name='максимальная скорость (км/ч)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')

    def __str__(self):
        return f'{self.model}'


class CarImage(models.Model):
    """Модель изображения автомобиля."""
    class Meta:
        verbose_name = 'изображение автомобиля'
        verbose_name_plural = 'изображения автомобилей'

    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='cars', verbose_name='автомобиль')
    image = models.ImageField(upload_to=car_images_directory_path, verbose_name='изображение')
    description = models.TextField(blank=True, verbose_name='описание')

    def __str__(self):
        return str(self.pk)

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Brand, Car, CarImage


class BrandsListView(ListView):
    model = Brand
    template_name = 'shop/brands.html'
    context_object_name = 'brands'

class BrandDetailsView(DetailView):
    model = Brand
    template_name = 'shop/brand_details.html'
    context_object_name = 'brand'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.filter(brand=self.object).all()
        return context

class CarsListView(ListView):
    queryset = Car.objects.select_related('brand')
    template_name = 'shop/cars.html'
    context_object_name = 'cars'

class CarDetailsView(DetailView):
    model = Car
    template_name = 'shop/car_details.html'
    context_object_name = 'car'

shop/templates/shop/brand_details.html
{% extends 'base.html' %}

{% block title %}
    {{ brand.model }}
{% endblock %}

{% block body %}
    <h1>Подробная информация о марке автомобиля</h1>
    <p>Описание: {{ brand.description }}</p><br>

    <div>
        {% for car in cars %}
            {% if car %}
                <strong>Вы можете посмотреть модели автомобилей данной марки:</strong>
                <p><a href="{% url 'shop:car_details' pk=car.pk %}">{{ car }}</a></p><br>
            {% endif %}
        {% endfor %}
    </div>

    <p><a href="{% url 'shop:brands' %}">Вернуться к списку марок автомобилей</a></p>

{% endblock %}

shop/templates/shop/brands.html
{% extends 'base.html' %}

{% block title %}
    Марки автомобилей
{% endblock %}

{% block body %}
    <h1>Марки автомобилей</h1>
    <h3>На нашем сайте представлены следующие марки китайских автомобилей:</h3>
    <div>
    {% if brands %}
    {% for brand in brands %}
        <div>
            <p><img src="{{ brand.image.url }}" width="120" height="90" align="left" hspace="10" alt="Логотип"></p>
            <p>Название: {{ brand.title }}</p>
            <p>Страна: {{ brand.brand_country }}</p>
            <p><a href="{% url 'shop:brand_details' pk=brand.pk %}">Посмотреть описание марки</a></p>
        </div>
    {% endfor %}

    {% else %}
        <p>Пока не было добавлено ни одной марки автомобиля</p>
    {% endif %}
    </div>
{% endblock %}

shop/templates/shop/car_details.html
{% extends 'base.html' %}

{% block title %}
    {{ car.brand }} {{ car.model }}
{% endblock %}

{% block body %}
    <h1>Подробная информация об автомобиле {{ car.brand }} {{ car.model }}</h1>
    <p>Класс автомобиля: {{ car.car_class }}</p>
    <p>Количество дверей: {{ car.doors_qty }}</p>
    <p>Количество мест: {{ car.seats_qty }}</p>
    <p>Коробка: {{ car.transmission }}</p>
    <p>Мощность двигателя: {{ car.engine_power }} л.с.</p>
    <p>Объём двигателя: {{ car.engine_capacity }} л</p>
    <p>Привод: {{ car.drive }}</p>
    <p>Расход: {{ car.consumption }}</p>
    <p>Объём багажника: {{ car.trunk_volume }} л</p>
    <p>Объём топливного бака: {{ car.fuel_tank_capacity }} л</p>
    <p>Максимальная скорость: {{ car.max_speed }} км/ч</p>
    <div>
        <a href="{% url 'shop:brand_details' pk=car.brand.pk %}">Вернуться на предыдущую страницу</a>
    </div>

{% endblock %}

shop/templates/shop/cars.html
{% extends 'base.html' %}

{% block title %}
    Автомобили
{% endblock %}

{% block body %}
    <h1>Автомобили</h1>
    <h3>На нашем сайте представлены следующие автомобили:</h3>
    {% if cars %}
        {% for car in cars %}
        <div>
        <p><img src="{{ car.preview.url }}" height="180" width="280" align="left" hspace="10" alt="Превью автомобиля"></p>
            <p>Марка: {{ car.brand }}</p>
        <p>Модель: {{ car.model }}</p>
        <p>Цена: {{ car.price }} руб.</p>
        <p>Скидка: {{ car.discount }}%</p>
            <a href="{% url 'shop:car_details' pk=car.pk %}">Посмотреть подробную информацию об автомобиле</a>
        </div>
            <div>
                <a href="{% url 'shop:brands' %}">Вернуться к списку марок автомобилей</a>
            </div><br>
        {% endfor %}
    {% else %}
        <p>Пока не было добавлено ни одного автомобиля</p>
    {% endif %}
{% endblock %}